# 生产环境配置
spring:
  resources:
    static-locations: file:./src/main/resources/static/
  thymeleaf:
    cache: false
    prefix: file:./src/main/resources/templates/

server:
  port: 8080
  servlet:
    context-path: /

ragflow:
  api:
    base-url: http://192.168.1.131:9380

logging:
  level:
    org.springframework.web: DEBUG    # 调试静态资源加载
    org.springframework.core.io: DEBUG
    com.example.service: DEBUG