- userId: "13612345678"  # 用户zjts@qq.com
  token: "token-zjts"
  apiKey: "ragflow-JhMGQwYjRlNDA1YjExZjBiNjljMWI2YT"
  applications:
    process: "cdaacb8c41f111f09f3913c504f0ae96"
    product: "be2bfde241c011f0bff0c1a468e0fb80"
    data: "af2068f441ef11f0abbcb714da4bbcd2"

- userId: "13761389910"  # 用户28271946@qq.com
  token: "token-bruce"
  apiKey: "ragflow-ZjODU3Y2MwM2I5YTExZjBiYjIxMDI0Mm"
  applications:
    process: "chatid4"
    product: "chatid5"
    data: "chatid6"

- userId: "13812345678"  # 用户yuehan@qq.com
  token: "token-yuehan"
  apiKey: "ragflow-M1NGE2YWUyM2ExMTExZjA4MjFhMDI0Mm"
  applications:
    product: "chatid7"
    process: "chatid8"
    data: "chatid9"

- userId: "13812345678"  # 本地配置 28271946@qq.com
  token: "token-dev"
  apiKey: "ragflow-IzYjFkM2EwMDQ4ZjExZjBhNmJmMDI0Mm"
  applications:
    product: "ac4df552048b11f0b44b0242ac120006"
    process: "34e07a0e142511f08b7a0242ac120007"
    data: "e3c93b4c3ad011f0837e0242ac120003"


